
version: '3'

services:
  webServer:
    image: nginx:1.17.10
    container_name: nginx_container
    depends_on:
        - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  api:
    build: .
    container_name: api_container
    command: python backend/manage.py runserver 0.0.0.0:5001
    ports: 
      - "5001:5001"
    restart: on-failure