version: '3'

services:
  proxy:
    build: 
      context: ./docker/proxy
    container_name: nginx_container2
    restart: always
    depends_on:
        - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    environment:
      - DOMAIN=$ALLOWED_HOSTS

  certbot:
    build: 
      context: ./docker/certbot
    command: echo "Skipping.."
    environment:
      - EMAIL=$ACME_DEFAULT_EMAIL
      - DOMAIN=$ALLOWED_HOSTS
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - proxy

  api:
    build: .
    container_name: api_container2
    depends_on:
      - db
    environment:
      - SECRET_KEY=$SECRET_KEY
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
    volumes:
      - ./data/db:/code/data/db
      - ./backend/:/code/backend
    command: bash -c "bash run.sh"
    # ports: 
    #   - "8000:8000"
    restart: on-failure

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    container_name: db_container2
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    # ports:
    #   - '5432:5432'

volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs: